### ISSUE TITLE
Problem with the width in console? (short lines)

### ISSUE THREAD

**Issue by maciejczyzewski** [commander-rb/commander#11]
I worked on the old version of commander. (the one from before the transfer to _commander-rb_) 
When I did the update, I notice this strange view: (short lines)

![LOL](https://dl.dropboxusercontent.com/u/103345209/Screenshots/Screenshot%202015-04-06%2014.58.06.png)

What's wrong??? Maybe someone knows?

**Comment by ggilder** [comment]
Hmm, we did have a change to the help formatter recently: https://github.com/commander-rb/commander/pull/9

Can you try running this with commander 4.3.2 (rather than the master branch) and let me know if the problem persists?

**Comment by maciejczyzewski** [comment]
I use commander  __4.3.2__! :cry:

**Comment by ggilder** [comment]
Is there a difference with 4.3.1? If you can pinpoint the version where this changes, that would help narrow it down.

**Comment by ggilder** [comment]
Actually, I'm thinking this may be an issue with the updated HighLine dependency. Can you try adding the following to your program after any `require` statements?

```ruby
puts "Terminal dimensions: #{HighLine::SystemExtensions.terminal_size}"
```

**Comment by maciejczyzewski** [comment]
Results:

 - Last working version of commander is __4.3.0__!
 - Answer for you question: ```Terminal dimensions: [29, 87]``` (ok)

Checked using RVM ```ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-darwin14.1.0]```

**Comment by maciejczyzewski** [comment]
Solved! Change this [#L20](https://github.com/commander-rb/commander/blob/master/commander.gemspec#L20) to:
```
s.add_runtime_dependency('highline', '1.6.21')
```
(proved by local build, should report it as bug at _highline_ repository)

**Comment by ggilder** [comment]
Ok, sounds like a bug with HighLine then if those dimensions are wrong for your terminal. Can you file an issue there and link it for reference to this issue?

**Comment by abinoam** [comment]
It's probably a regression in HighLine.
Reporting columns and lines in reverse order.
https://github.com/JEG2/highline/pull/139

**Comment by abinoam** [comment]
Fix released at https://github.com/JEG2/highline/pull/139#issuecomment-94320055 
Could @maciejczyzewski  and the others please confirm is working in your setups?

**Comment by ggilder** [comment]
I've released 4.3.3 with an update to use highline 1.7.2. @maciejczyzewski please let me know if you're still seeing any problems.

**Comment by maciejczyzewski** [comment]
@ggilder @abinoam now it's working :+1:

**Comment by abinoam** [comment]
Great :+1:
