### ISSUE TITLE
documentation / clarification for subcommands

### ISSUE THREAD

**Issue by neurogenesis** [commander-rb/commander#14]
The features mention the use of multi-word commands / subcommands, but it's not immediately clear to those new to Ruby as to how that would be done.

Would it be possible to update the documentation to reflect subcommand examples?

Thank you in advance!

**Comment by oschrenk** [comment]
Have the same question. Would be great to see some examples.

**Comment by ggilder** [comment]
There are a few examples of multi-word commands in the readme: https://github.com/commander-rb/commander#command-aliasing

I agree that it's not very explicit, though. If you would like to put together a pull request to add clearer documentation, that would be awesome!
