### ISSUE TITLE
user_interaction: Use RbConfig instead of obsolete and deprecated Config

### ISSUE THREAD

**Issue by sts** [commander-rb/commander#24]
The change from ffc4e0d1b47b8d04ad271f19eaef2c9154066924 included in 4.3.6 triggers a warning on Ruby 2.1.5p273 (Debian Jessie). Reversing the change, fixes the warning:

```/var/lib/gems/2.1.0/gems/commander-4.3.7/lib/commander/user_interaction.rb:333:in `const_get': Use RbConfig instead of obsolete and deprecated Config.```

**Comment by ggilder** [comment]
Fixed in 4afaefc321f196e54a61840ef6cd6b85e5c3e51d, will release soon

**Comment by ggilder** [comment]
Released as 4.3.8
