### ISSUE TITLE
Provide heredoc helper

### ISSUE THREAD

**Issue by sts** [commander-rb/commander#25]
It would be great if commander would provide a helper to unintend a String created with a heredoc. Some seem to solve this "elegantly" via a core_ext to String:

```ruby
class String
  def unindent
    gsub(/^#{scan(/^\s*/).min_by{|l|l.length}}/, "")
  end
end

command :test do
  message = <<-EOM.unindent
  This is a test message! The left indent
  gets stripped automatically!
  EOM
end
```

**Comment by ggilder** [comment]
This is already provided in ActiveSupport, I'd probably suggest just using that: http://edgeguides.rubyonrails.org/active_support_core_extensions.html#strip-heredoc
