### ISSUE TITLE
Nesting options or adding flags to options?

### ISSUE THREAD

**Issue by lebogan** [commander-rb/commander#34]
Does this even make sense?:

I'm building a simple Sinatra application builder with Commander. On my option to build with the inline method, I want to choose between Slim or Erb. It would go something like this:
```
$ sincab init --inline -s myapp
or
$ sincab init --inline -e myapp
```
Those two flags would only belong to the --inline option.

Thanks for any thoughts on this.

**Comment by ggilder** [comment]
It's an interesting use case — albeit one that almost seems too complicated for a command-line tool 😉 

In general I don't think I've seen a command-line app framework that supports something like this, but there's a few workarounds I've seen:

1. Each of the flags is just a normal option, and your command does some validation, e.g. raise an error if you use `-s` without `--inline`, or raise an error if you use `--inline` without one of the `-s`/`-e` flags
2. Flatten the nesting so that instead of `--inline` you have `--inline-slim` and `--inline-erb`

**Comment by lebogan** [comment]
As always, thanks for your insight. Commander can handle this!:-) I'm
testing both options so I will close this issue.

Lewis Bogan

On Fri, 2016-08-12 at 14:14 -0700, Gabriel Gilder wrote:
> > It's an interesting use case — albeit one that almost seems too
complicated for a command-line tool 😉 
> 
> > > In general I don't think I've seen a command-line app framework that
supports something like this, but there's a few workarounds I've
seen:
> 
> 
> > > Each of the flags is just a normal option, and your command does some
validation, e.g. raise an error if you use -s without --inline, or
raise an error if you use --inline without one of the -s/-e flags
> > Flatten the nesting so that instead of --inline you have --inline-
slim and --inline-erb
> 
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/commander
-rb/commander","title":"commander-rb/commander","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/commander-
rb/commander"}},"updates":{"snippets":[{"icon":"PERSON","message":"@g
gilder in #34: It's an interesting use case — albeit one that almost
seems too complicated for a command-line tool 😉 \r\n\r\nIn general 
I don't think I've seen a command-line app framework that supports
something like this, but there's a few workarounds I've
seen:\r\n\r\n1. Each of the flags is just a normal option, and your
command does some validation, e.g. raise an error if you use `-s`
without `--inline`, or raise an error if you use `--inline` without
one of the `-s`/`-e` flags\r\n2. Flatten the nesting so that instead
of `--inline` you have `--inline-slim` and `--inline-
erb`"}],"action":{"name":"View Issue","url":"https://github.com/comma
nder-rb/commander/issues/34#issuecomment-239561387"}}}
