### ISSUE TITLE
[Question] How to create a command suite with two levels of commands.

### ISSUE THREAD

**Issue by ignazioc** [commander-rb/commander#35]
Thanks for the great job.
I'm wondering if with this tool is possible to define two levels of commands. For example:

    git remote add
    git remote rm

Where `git` is the name of the script, `remote` is the 1st level of command and `add` | `rm` are the actual commands.

Thanks.

**Comment by azgul** [comment]
Curious about this too! I realize that you can do
```
command 'commandName subcommandName'
```
but this litters commandName --help heavily if there are is a lot of sub commands for each command :(

**Comment by ignazioc** [comment]
I switched from `commander` to `GLI` that supports this syntax by default.
