### ISSUE TITLE
Revisit documentation / clarification for subcommands #14

### ISSUE THREAD

**Issue by lebogan** [commander-rb/commander#48]
I have been playing around with the command aliasing feature and would like to take a crack at adding to the documentation. From what I can see this isn't a true sub-command structure but the potential for organizing commands with it is awesome. 

This is what a sample help screen looks like:
```
bundle exec projman help
...
Commands:
  help ...

Aliases:                                                                      
    project list project list                                                 
    project new  project new                                                    
    project show project show                                                   
    task add     task add                                                       
    task delete  task delete                                                   
    task update  task update                                                   
```
I appreciate any advice you have on this matter.

Thank you.

**Comment by ggilder** [comment]
If you're interested in adding to the docs I would say take a shot at editing the section in the README — anything clarification you can add would be great!

**Comment by lebogan** [comment]
I would like to reopen this. The project that spawned this request is working well. Just need to document it for some of my former colleagues. My pull request is failing the Travis integration and I need some help. 

Thank you.
