### ISSUE TITLE
Display --help on missing option

### ISSUE THREAD

**Issue by mastermindg** [commander-rb/commander#53]
I have a command with a required option. How can I display the help page to the user if this option is not set?:

```
    command :test do |c|
      c.syntax = 'Test command'
      c.description = 'Test command'
      c.option '--prefix STRING', String, 'Adds a prefix to test'
      c.action do |args, options|
        raise ArgumentError.new("Prefix is required!") unless options.prefix
        testMeth
      end
    end
```

**Comment by lebogan** [comment]
mastermindg,
Not sure what your use case is. If you really need help to display, try this:
```
        unless options.prefix
          puts 'Prefix is required!'
          command(:help).run(:test)
          exit 1
        end
  ```
Please note, this is not a public (published) option. I dug this out of the commander source code. You might want to seriously review your use case as this solution may not be very portable. 

Commander out-of-the-box is pretty complete and rethinking my process has helped me a lot. I am not a developer but a retired old-guy network specialist. Take this with several grains of salt and a pint of good brew.

Lewos

**Comment by ggilder** [comment]
It seems like @lebogan 's workaround would do the trick. Closing the issue
