### ISSUE TITLE
Deprecation warning when used together with pg

### ISSUE THREAD

**Issue by skyfmmf** [commander-rb/commander#57]
When using both, your gem and the pg gem (for PostgreSQL) in a project, I get a deprecation warning from pg as they have deprecated some of their constants. To get the deprecation warning when using the old constants, pg moved them in a special file (
https://bitbucket.org/ged/ruby-pg/src/master/lib/pg/deprecated_constants.rb) that is not needed normaly. But as you are walking through all constants (https://github.com/commander-rb/commander/blob/master/lib/commander/user_interaction.rb#L334), also the deprecated constants are accessed. 

Maybe you could add them to your deprecation list.

**Comment by ggilder** [comment]
Hi, it seems that the original repository for the gem you mentioned has been deleted. If this is still an issue, please reopen and identify the deprecated constants that should be ignored. Thanks!
