### ISSUE TITLE
Inline --help instead of man page

### ISSUE THREAD

**Issue by valleybay** [commander-rb/commander#58]
Would it be possible to have --help show inline, like with many other CLI-tools, instead of it opening a man page?

**Comment by gmontard** [comment]
👍

**Comment by lebogan** [comment]
Hello @valleybay,

Are you looking for a less verbose help screen? Which CLI-tools are you refering to? Something like?:
```
$ myapp --help
Usage:  myapp -flags args
```
And have the longer style available with:
```
$ myapp --help --verbose
Usage: blah bah blah
blah
blah
```
Or maybe for the less verbose style, something like?:
```
program :help_formatter, Commander::HelpFormatter::SuperTerminalCompact
```

**Comment by gmontard** [comment]
The thing that annoy me is the fact that the help open kind of a "new page" in the terminal, it's not displayed inline. Am I missing something?

**Comment by ggilder** [comment]
I believe you're talking about the behavior where the help text opens in your terminal's PAGER program (usually `less`) if it is too long to be displayed in the height of the current terminal. You can disable that behavior by setting the following flag in your program:

```ruby
program :help_paging, false
```

I see that this option is not very clearly documented... if you want to submit a patch to the readme please do!
