### ISSUE TITLE
--

### ISSUE THREAD

**Issue by badeball** [commander-rb/commander#75]
Double dash as described in https://github.com/tj/commander/issues/34, seems to be broken after 4.4.0, specifically after https://github.com/commander-rb/commander/commit/420ffa9.

The mentioned example yields `-x` as an option rather than argument, when used in conjunction with double dash.

Additionally, it fails to parse EG. `ruby test.rb foo -- --foo`.

**Comment by ggilder** [comment]
Somehow I missed this issue... I just tried the test case you mentioned and the behavior does seem to be broken. It appears that it was working with version 4.3.0, so I'll take a look and see if I can figure out where this regressed. Thanks for reporting this issue, and sorry for taking so long to notice it!

**Comment by ggilder** [comment]
Breaks between 4.3.8 and 4.4.0; possible commits breaking this are f64289b, 38a5817, 420ffa9, 9740771

**Comment by ggilder** [comment]
Fixed in version 4.5.0 (just released).
